name: Generate Matrix Contribution Graph

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # runs daily
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Matrix Contribution Graph
        uses: N1k0droid/matrix-svg-contrib@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: MD-Mushfiqur123
          output_dir: dist

      - name: Push Matrix Graph to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
